### ISSUE TITLE
Add social URL in the footer

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#113]
In the footer between Sitemap and Legal add this links in order.

- YouTube: https://www.youtube.com/channel/UCgRepT4AO6mGsJaWsS_mHbA
- Twitter: https://twitter.com/0x4447
- LinkedIn: https://www.linkedin.com/company/0x4447

**Comment by davidgatti** [comment]
@tolgaouz where is the PR for this one? Close it only once you make a PR.

**Comment by tolgaouz** [comment]
Ah, I was actually waiting for you to make other PRs before opening this one. I guess I thought this one might cause some merging issues if merged before the other ones.
