### ISSUE TITLE
OG tuning

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#131]
I made a branch called `dg/og-tags` where I added separated OG files to be linked. So we need to link to those files + we have to do the following:

- add the `type` tag to the whole page and set it to, `website`
- Add the resolution tags for the og images, which is going to always be `720x480`

**Comment by tolgaouz** [comment]
I guess you haven't published that branch yet David, I'm not able to see it

**Comment by davidgatti** [comment]
Sorry. done.
