### ISSUE TITLE
The post layout question

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#135]
Why is it constructed this way? Why repeat the nav etc, it should be injected in to the default body view.

**Comment by tolgaouz** [comment]
I don't actually remember why I did it this way, probably because every jekyll project has specific layouts for post views.

**Comment by davidgatti** [comment]
OK, we will have to talk about this at a later date.

**Comment by tolgaouz** [comment]
Should I close this?
