### ISSUE TITLE
Social preview is not working on Linked In.

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#138]
![Screen Shot 2020-07-28 at 2 23 44 PM](https://user-images.githubusercontent.com/411114/88664942-20cf6000-d0de-11ea-8b8b-adb3458e0523.png)

Something happened, where now LinkedIn can't make a preview of the link, this require some investigation to figure out what what is wrong. Spend 3h on it, and then lets have a chat about it.

**Comment by vosaul** [comment]
test in Linkedin
https://test-8e6c05.netlify.app/articles/knowledge/should-i-go-all-in-with-serverless.html
![image](https://user-images.githubusercontent.com/28349676/90250653-108ce400-de45-11ea-88c6-24746156c508.png)
