### ISSUE TITLE
New title structure

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#139]
We can have a chat about this to better explain.

```
AWS Cloud Consulting - 0x4447
AWS Cloud Consulting - Schedule A Meeting - 0x4447
AWS Cloud Consulting - Contact Us - 0x4447
AWS Cloud Consulting - Our Articles - 0x4447
AWS Cloud Consulting - Knowledge - 0x4447
CloudFormation Tips and Tricks - 0x4447
```

**Comment by vosaul** [comment]
Do you mean the <title> tag in the <head> section?

**Comment by davidgatti** [comment]
Yes

**Comment by vosaul** [comment]
Okay, then I propose to abandon the SEO plugin, I will prescribe everything manually in the <head> section and we will have full control over the SEO tags.

**Comment by vosaul** [comment]
P.S. manually I mean to write a Liquid script, and SEO tags will be generated automatically

**Comment by davidgatti** [comment]
OK, makes sense.

**Comment by vosaul** [comment]
so I'm starting

**Comment by vosaul** [comment]
I implemented everything, just please explain the first and last lines, where to apply it

**Comment by vosaul** [comment]
I'll change it, not a problem
I understand your comment that the "Articles" refers to the page named "articles" and not the individual articles

**Comment by davidgatti** [comment]
Yes, and once the PR open, lets keep the conversation in the PR made and not on the closed issue.
