### ISSUE TITLE
Separate data from HTML to Yaml

### ISSUE THREAD

**Issue by vosaul** [0x4447-office/0x4447_webpage_consulting#146]
On the home page, I suggest separating the data from HTML to Yaml file and simplifying the HTML using Liquid

**Comment by davidgatti** [comment]
What is Liquid?

**Comment by vosaul** [comment]
https://shopify.github.io/liquid/
it using in Jekyll
![image](https://user-images.githubusercontent.com/28349676/90340206-2fcf7100-dfff-11ea-90f3-3ce2a8b7df56.png)
Liquid in HTML in index.html

**Comment by davidgatti** [comment]
A ok, thank you for the explanation.

**Comment by vosaul** [comment]
can I do that?

**Comment by davidgatti** [comment]
YEs, please, I did assigned you to the issue, so it is your to make.
