### ISSUE TITLE
Section "Our customers speak volumes about us"  is displayed incorrectly. 

### ISSUE THREAD

**Issue by vosaul** [0x4447-office/0x4447_webpage_consulting#148]
Section "Our customers speak volumes about us"  is displayed incorrectly. 
I suggest to do it in as a slideshow or as a grid.
![image](https://user-images.githubusercontent.com/28349676/90319313-a4db7180-df3f-11ea-975a-db9db4d56295.png)

**Comment by davidgatti** [comment]
This is part of the UI that I bought, please don't change this.

**Comment by vosaul** [comment]
I'm sorry, maybe I didn't understand something, but the carousel is set up incorrectly - out of eight reviews it shows only four and the slides do not flip, the picture is static and everything is shifted to the right. Is it only displayed on my laptop like that?  After my adjustment, the slides were centered and flipped.
