### ISSUE TITLE
Fine tune the contact page

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#153]
Two small changes in the contact page.

![Screen Shot 2020-08-20 at 11 07 23 AM](https://user-images.githubusercontent.com/411114/90750968-d18fe000-e2d5-11ea-8dc0-4a08a61ae90e.png)

**Comment by vosaul** [comment]
A list of industry exists? 

Do you mean aws_services.yaml? 

Or should this list be created?

**Comment by davidgatti** [comment]
The lsit should be created, do a google search for something, anything is OK, I will fine tune it myself.

**Comment by vosaul** [comment]
Ok
