### ISSUE TITLE
Fix the style in the Article list

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#154]
Right now the cards are out of sync, the need to look the same in the way described in the image.

![Screen Shot 2020-08-20 at 11 02 26 AM](https://user-images.githubusercontent.com/411114/90751087-f7b58000-e2d5-11ea-8514-f92821fdcf4e.png)

**Comment by vosaul** [comment]
Did I understand correctly?
Or do it in the form of a grid?
![image](https://user-images.githubusercontent.com/28349676/90792238-e76fc600-e312-11ea-9a14-fe5558da2f17.png)

**Comment by davidgatti** [comment]
Understood incorrectly, not sure why you removed the images :) did say nothing about them. If this issue is unclear we can discuss it on Monday.

**Comment by vosaul** [comment]
I thought that the inscription "this must be canceled" refers to the picture. Was a little surprised :)

**Comment by davidgatti** [comment]
We are almost there, some images have this resolution `500x430` and this was the resolution original to the template that we are using, over time I started cropping the images, but all was working OK, because the cards had a fixed height, then the previous developer did change something, and now the cards did shrink to the highs thing within them. 

I want the cards to have a fixed height, so if the image has the exact resolution or has a smaller height, the image will always be centered.

I hope this makes sesne.

**Comment by vosaul** [comment]
![image](https://user-images.githubusercontent.com/28349676/91443612-3c17c180-e87c-11ea-8c89-085786a91515.png)

**Comment by vosaul** [comment]
images are vertically and horizontally centered
