### ISSUE TITLE
Display the contact form at the end of the article

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#155]
Makes it so there is only one code base, so changes in the form will be automatically reflected in both.

![Screen Shot 2020-08-20 at 11 09 21 AM](https://user-images.githubusercontent.com/411114/90751191-1ae02f80-e2d6-11ea-9ed1-d6ed862cb24e.png)

**Comment by vosaul** [comment]
I copied the contact form from the contact page. But it seems that it should be simplified, remove the banner from the form in the article.
![image](https://user-images.githubusercontent.com/28349676/90769488-ffd2e700-e2f8-11ea-9c77-189313a939fd.png)

**Comment by vosaul** [comment]
somehow
only slightly customize the shape (size, background)
I think for the article so it will be better
![image](https://user-images.githubusercontent.com/28349676/90771253-ab7d3680-e2fb-11ea-868d-c210719d5848.png)

**Comment by davidgatti** [comment]
Perfect as long as there is one code base.

**Comment by vosaul** [comment]
I will separate the banner from the form, it will be possible to use with a banner or without
