### ISSUE TITLE
Fix Contact style problems

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#159]
![Screen Shot 2020-08-25 at 9 45 56 AM](https://user-images.githubusercontent.com/411114/91147114-19d54680-e6b8-11ea-811d-a57c6b90c1b3.png)

- [ ] Set the same height between components
- [ ] Set the text area to 300px heigh

**Comment by vosaul** [comment]
Sorry, I'm used to calling the distance between blocks as a gap, so I misunderstood. It was not possible to clarify, so I did as I understood.

Now I want to clarify - initially, the height of textarea was 163px.
Revert to previous height or make 300px as in your comment?

163px
![image](https://user-images.githubusercontent.com/28349676/91156947-60816b80-e6cd-11ea-90b0-a641e7c5dadd.png)

300px
![image](https://user-images.githubusercontent.com/28349676/91157421-fa491880-e6cd-11ea-801b-cf5950dfc02b.png)

**Comment by davidgatti** [comment]
OK, understood. and in this case let set it up to 300px.

**Comment by vosaul** [comment]
ok
