### ISSUE TITLE
OG are all messed up again

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#172]
@vosaul do you understand what is the purpose of https://ogp.me/ ?

**Comment by vosaul** [comment]
The Open Graph protocol developed by the Facebook team to correctly display the page in FB.
If you fill in these attributes, then in the post with a link to the page there will be a picture, description, etc.
There are similar tags for Twitter and Google.
We use all these tags for the previous site.
![image](https://user-images.githubusercontent.com/28349676/92334515-58dfa080-f097-11ea-8d60-9b4a41ef49df.png)

**Comment by vosaul** [comment]
![image](https://user-images.githubusercontent.com/28349676/92334721-53835580-f099-11ea-9eef-8a9f3e6a4de1.png)

**Comment by davidgatti** [comment]
If you know what they are, why then the are still all messed up on the consulting page? All pages on the page, should have individual tags for the specific page, and yet they don't. I don't understand why this is such a problem?
