### ISSUE TITLE
Contact drop downs don't look good

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#177]
![Screen Shot 2020-11-03 at 8 35 57 AM](https://user-images.githubusercontent.com/411114/97959448-b1899c00-1daf-11eb-93e4-e7ed61786726.png)

This dose not look good now, I'm open to suggestion to make this contact drop down look better.

**Comment by edhenderson** [comment]
Yeah, its maybe got zapped by the theme upgrade, I shall investigate.

**Comment by edhenderson** [comment]
## Diagnosis

1. Upgrading Landkit (v1.0.0 to v1.2.0) has also upgraded Bootstrap (v4.3.1 to v4.5.0).

2. Landkit has introduced a `dropdown` component in the new version, which didn't exist before - https://landkit.goodthemes.co/docs/dropdowns.html - this is not the kind of dropdown you use but the name is the same.

3. You use Bootstrap-select for YOUR dropdowns.

This name clash caused a nasty conflict.

I _should_ be able to patch these changes and get it back looking almost the same as before. Is that ok?

**Comment by davidgatti** [comment]
They don't have to look the same, I want them to look good in tune with the whole UI, so if they introduced a nice drop down, lets use that.

**Comment by edhenderson** [comment]
Right, understood, let me see if I can use a new dropdown from the new theme (upgrade), failing that I'll fallback to making it look as good as possible.

**Comment by edhenderson** [comment]
So investigation complete. I've pulled the code through a microscope.

Some definitions, apologies if you know this:

- `bootstrap-select` - https://developer.snapappointments.com/bootstrap-select/ - 3rd party library that makes your regular Bootstrap dropdowns into fancy multi-select, searchable things (nothing to do with Landkit or official Bootstrap)
- Bootstrap - CSS framework
- Landkit - theme built on top of and using Bootstrap

Looking at https://landkit.goodthemes.co/docs/dropdowns.html - which is what we are using, OUR dropdowns look exactly like they do here. This is good.

EXCEPT we are using the additional library bootstrap-select as well.

(Remember that before the Landkit theme upgrade, dropdowns did not exist in Landkit, so `bootstrap-select` was working fine on top of (essentially) Bootstrap dropdowns.)

Landkit only caters for the simple use case, check the demo in the link, not the enhanced `bootstrap-select` version.

This is why we get crappy padding/margins.

So in lieu of waiting and hoping Landkit, Bootstrap and `bootstrap-select` have a 3-way (unlikely) we need to do our best.

`bootstrap-select` is designed to be used on top of Bootstrap, not on top of Landkit on top of Bootstrap.

So my opinion is to add some custom styles to temper back the CSS best we can. I will do this.

**Comment by davidgatti** [comment]
Thank you for the detailed explanation and I like the result.
