### ISSUE TITLE
Straight line

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#182]
When you visit the article page, and scroll down till the end, there will be a gray area with suggestions to other articles, this gray area has the top part not as a straight line, but it is curved, I think the template had it straight if I'm not mistaken.

**Comment by edhenderson** [comment]
@davidgatti As per https://landkit.goodthemes.co/blog-post.html there is a curve. This is replicated in https://consulting.0x4447.com/articles/how_to/how-to-hire-the-technical-team.html

Let me know if you want to retain the curve or I can remove it for articles.

**Comment by davidgatti** [comment]
OK, I see, but on my page, there are 2 curves. one right after the article ends, end the other one in the footer, to much curving :) was the template implemented incorrectly back when, or am I missing something? Because the url of the template shared has the footer and the last section of the article page as one.

**Comment by edhenderson** [comment]
I see (about the curves), I'll remove the one that sneaked in.
