### ISSUE TITLE
Consistent margins across the whole site.

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#184]
Two developers worked on this, and wee keep not having one standard. What I like for you to do, is to check the template, see what is the margin set across the template, and apply it also on the site. so each page has consistent gaps between content. I don't know how to explain this, and I'm also tired to do so. Because I have no clue how to write this in different way anymore to make myself explain. I hope you can see the problem and come up with a solution.

![Screen Shot 2020-11-03 at 8 46 52 AM](https://user-images.githubusercontent.com/411114/97960161-2d381880-1db1-11eb-95c4-7aaeb935504d.png)

**Comment by edhenderson** [comment]
I understand whats happening here. I will find a solution.
