### ISSUE TITLE
Nice looking tags

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#19]
![Screen Shot 2020-03-28 at 3 08 55 PM](https://user-images.githubusercontent.com/411114/77825013-eb524000-7106-11ea-840f-24ea03ffabd6.png)

I'd like to use here a display name tag, so we can customize how the text looks, while preserving a functional URL.

**Comment by tolgaouz** [comment]
Turns out we can't do that, closing the issue
