### ISSUE TITLE
Expand beyond the default margins

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#195]
As you can see from the images bellow I want to expand the attached images and form beyond the default margins, I think it will look nice. What I want you to make sure, that the way you do this will be still compatible with the mobile view.

For example in the view the images go beyond the default margins: https://landkit.goodthemes.co/blog-post.html

![Screen Shot 2020-11-07 at 11 14 22 AM](https://user-images.githubusercontent.com/411114/98439169-46620180-20f0-11eb-8c5b-1aa6c7bfb385.png)
![Screen Shot 2020-11-07 at 11 15 39 AM](https://user-images.githubusercontent.com/411114/98439170-4a8e1f00-20f0-11eb-91d6-120942454004.png)

**Comment by edhenderson** [comment]
I shall make them go wider but still have a sensible cap on the max-width. And of course still work as before in mobile view.

**Comment by edhenderson** [comment]
The reason the images are wider in the template isn't because they are wider, its cause the content is thinner and the images are normal width. Your post is markdown, I'll need to see what I can do tomorrow but I don't think this will be easy.

**Comment by edhenderson** [comment]
I can make the form wider (see PR coming shortly) but making the image wider in the same style will unfortunately be a decent amount of effort. It will involve either:

- hacking the grid system
- a different grid
- adding HTML to the markdown article (to essentially close and open a section TWICE)

It's not gonna be pretty whatever way we do it. For one image (currently) is this effort going to be worth it?

**Comment by davidgatti** [comment]
no :)
