### ISSUE TITLE
Paralax for all

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#196]
I had no idea that the headers had a paralax effect, it seams previous developers did remove this feature. I'd like you to readd it, and also check why the effect is not working under chrome.  In safari it is working.

![Screen Shot 2020-11-07 at 11 16 13 AM](https://user-images.githubusercontent.com/411114/98439209-95a83200-20f0-11eb-96d2-35c57b1c1ed4.png)

**Comment by edhenderson** [comment]
Understood, I shall investigate. It may be that the theme only works in Safari, not Chrome.
