### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#197]
The tags did not get included.

![Screen Shot 2020-11-07 at 12 02 57 PM](https://user-images.githubusercontent.com/411114/98439319-74941100-20f1-11eb-95c3-b329732cb022.png)

**Comment by edhenderson** [comment]
Can you be more specific?

I think you asked me to remove the search. Are you asking me to reimplement the ability to click on categories?

Checking the code we have:

```
how_to, knowledge, experience
```

**Comment by davidgatti** [comment]
Right that was to remove the search input thing, but tags are tags :) so originally you clicked the tags, and saw articles jsut with that tag, can we re-enable that + display the tags on the home page of the article section?

**Comment by edhenderson** [comment]
We can do that yes. It might need a new page to do this but it will be a template based on the articles home page.
