### ISSUE TITLE
The metadate about the article is not centered

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#198]
This is the template, and on the live page, the content is not centered.

![Screen Shot 2020-11-07 at 12 03 24 PM](https://user-images.githubusercontent.com/411114/98439335-8aa1d180-20f1-11eb-8ece-bf70023a3cf1.png)

**Comment by edhenderson** [comment]
Understood. I think the removal of the avatar has caused this, i.e. bad that the template relied on the image to vertically centre, I will resolve.
