### ISSUE TITLE
Custom CSS for contact form in article

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#201]
This page shows at the end a different view of the contact page: https://landkit.goodthemes.co/career-single.html - could we do it the same, and only show this version in the article section? Or this would be to complicated to to with Jekyll?

![Screen Shot 2020-11-07 at 12 20 07 PM](https://user-images.githubusercontent.com/411114/98439668-b3c36180-20f3-11eb-94d6-0c0e81701d25.png)

**Comment by edhenderson** [comment]
Yes, we could show something different at the end of an article. Do you want this exact form (in screenshot?)

**Comment by davidgatti** [comment]
Yes the same style. This is from the template.

**Comment by edhenderson** [comment]
This seems to be a form for a job application, is that what you want at the end or should it be more of a contact form?

**Comment by davidgatti** [comment]
it should be the contact form from the contact page.

**Comment by edhenderson** [comment]
Right good, thought so. I will resolve this later today. Thanks.
