### ISSUE TITLE
White paper page for clients

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#202]
As the last thing, I want to add a new sub page where I will have a white paper describing what I did for each client. Right now on the home page there is a carrousel of clients. I want to replace the URL to the client page, with `read white paper` and when you click on it this view is going to be used: https://landkit.goodthemes.co/career-single.html

![Screen Shot 2020-11-07 at 12 22 52 PM](https://user-images.githubusercontent.com/411114/98439786-77443580-20f4-11eb-9b45-a20a8ced7ced.png)

**Comment by edhenderson** [comment]
Just to clarify some questions:

1/ Each client on the home page carousel will link to a DIFFERENT page?
2/ Do you want the form too?
3/ Is the White Paper going to be a PDF or on the actual page?

**Comment by davidgatti** [comment]
1. different link, same concept as articles
2. if you are talking about the contact form, actually why not.
3. actual page, from the template linked.

**Comment by edhenderson** [comment]
Right got it. Home page will now have links to, e.g. /clients/atkins and that will use the template above. At the bottom of each page will be the contact form (rather than the job application form).

I will leave placeholder content for you to fill later.
