### ISSUE TITLE
Article page got scrambled

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#215]
Not sure what happened but after merging the tag PR this is the view that I now have, I'd like to have the original view.

![Screen Shot 2020-11-10 at 9 26 06 AM](https://user-images.githubusercontent.com/411114/98648627-ced1e380-2336-11eb-9777-caad05e434a8.png)

**Comment by edhenderson** [comment]
Dam that's not good. Not sure what happened there. I will investigate.
