### ISSUE TITLE
Image resolutions

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#217]
The images that I have for the articles have a resolution that was designed for the old template. Now since we are using the new one, all the resolutions and proportions are bit off, based on the template, could you write all the 3 resolutions that would be ideal for the layout that we have now?

- Mini image for the article card
- Medium image for the featured article
- The big one for the header, for example now with the non white background it is obvious the resolution is not right.

**Comment by edhenderson** [comment]
Suggested sizes:

- mini, 320px wide
- medium 500px wide
- max 1100px wide

These are maximum sizes of course, when the page gets responsively smaller they will be shrunk down by the browser/theme/CSS.

Hope that helps. No Pull Request for this one.
