### ISSUE TITLE
Different bg color for other colors

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#220]
The section now is the same color as the BG.

![Screen Shot 2020-11-11 at 9 52 49 AM](https://user-images.githubusercontent.com/411114/98791702-b977ba80-2405-11eb-8ea1-3d5e493b735c.png)

**Comment by edhenderson** [comment]
That is correct, what action would you like me to take?

**Comment by davidgatti** [comment]
take the color from the right and port it to the left, I know that your monitor can't display this, but trust me those are 2 different colors :) check the Hex.

**Comment by edhenderson** [comment]
Hey, my monitor was just misbehaving, it was a sunny day in the house! Ha!

**Comment by edhenderson** [comment]
Would you believe me if I told you those 2 colours were the same? They are both `bg-light` and its the colour of the entire body (the root of the document). Let me see what I can do instead...
