### ISSUE TITLE
Remove empty space if possible

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#223]
I know you don't have 100% control over this things, but if possible it be nice if you could see if this empty space can be removed.

![Screen Shot 2020-11-11 at 9 56 50 AM](https://user-images.githubusercontent.com/411114/98791809-dc09d380-2405-11eb-9096-ea24af5a8855.png)

**Comment by edhenderson** [comment]
Using https://help.calendly.com/hc/en-us/articles/360019861794-Common-embed-questions as a reference I discovered the height is passed in when we call the intergration. There is still a janky scrollbar and the space still exists on their side but I can't control that I'm afraid.
