### ISSUE TITLE
The LinkedIN link is for mobile

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#225]
Needs to be for desktops

![Screen Shot 2020-11-11 at 9 54 36 AM](https://user-images.githubusercontent.com/411114/98791960-11162600-2406-11eb-80e7-8045295f2b91.png)

**Comment by edhenderson** [comment]
This is how this works I am afraid.

I haven't found any official documentation from LinkedIn but I found at least half a dozen other sites doing this exactly the same way. This is even the way my employer does it.

See https://www.websiteplanet.com/webtools/sharelink/
See https://gist.github.com/apisandipas/74d396c7853b93f5f861091a2135d527
See https://www.mikestreety.co.uk/blog/build-your-own-share-this-component
See https://swimburger.net/blog/web/social-sharing-buttons-with-zero-javascript-to-twitter-reddit-linkedin-and-facebook#linkedin
:
and so on

It's not great I am afraid but this is where we are with it. 

What I can do (and what is in the PR is add some Javascript to pop it open in a new window), let me know how that works for you?
