### ISSUE TITLE
The rectangles of the white papers

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#226]
I need some extra details, a variable for:

- the name of the author of the feedback
- the URL to their site. 
- and display the logo at top of the company info

![Screen Shot 2020-11-12 at 9 21 32 AM](https://user-images.githubusercontent.com/411114/98919063-aed52800-24ce-11eb-9a5d-8c7dc684eed9.png)
![Screen Shot 2020-11-12 at 9 22 08 AM](https://user-images.githubusercontent.com/411114/98919069-b09eeb80-24ce-11eb-8d4b-c73257fb39b8.png)

**Comment by edhenderson** [comment]
Understood. I found a Landkit style for quotes.
