### ISSUE TITLE
White paper URL is not working

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#227]
https://consulting.0x4447.com/clients/atkins

you get page not found, we need the url to end with .html.

**Comment by edhenderson** [comment]
This is strange. I run `master` locally and it works fine. Is the production version `master`?

**Comment by edhenderson** [comment]
It's almost like my version locally and master build _slightly_ differently.

Mine builds to `/clients/atkins` - production / Github pages? build to `/clients/atkins.html`

They interpret the default differently. I will be explicit so there is no ambiguity.
