### ISSUE TITLE
Gaps in the white paper section

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#230]
There are two type of gaps that are bigger then gap at the top, in both cases the gap should be the same depending on the content of the page.

![Screen Shot 2020-11-12 at 11 49 41 AM](https://user-images.githubusercontent.com/411114/98930875-915b8a80-24dd-11eb-84b3-49922c36fec3.png)
![Screen Shot 2020-11-12 at 11 50 55 AM](https://user-images.githubusercontent.com/411114/98930887-94ef1180-24dd-11eb-900f-35c2458adeb2.png)

**Comment by edhenderson** [comment]
Yip, I can see the gap difference. This is how it is in the template - https://landkit.goodthemes.co/career-single.html - but I agree with you, it would be much better if they were consistent.
