### ISSUE TITLE
Extend background to full width and white

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#248]
![Screen Shot 2020-11-14 at 10 39 27 AM](https://user-images.githubusercontent.com/411114/99144664-ea572a00-2667-11eb-8522-8f7c6a5ee3cb.png)

**Comment by edhenderson** [comment]
I assume you mean on ALL article pages, not just this one?

**Comment by davidgatti** [comment]
Correct.
