### ISSUE TITLE
Improve Google Speed test

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#250]
Cloud you check the Google Speed https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fconsulting.0x4447.com%2F - and check what can be improved without having to do some drastic changes, by writing a list of things worth doing.

**Comment by edhenderson** [comment]
So the output here is a list of things to do, rather than to fix them?

**Comment by davidgatti** [comment]
For now yes, and then we can decide what is worth doing.

**Comment by edhenderson** [comment]
# Google Page Speed Improvements

Re: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fconsulting.0x4447.com%2F&tab=desktop

Most of the good advice is given on the page itself but in short, for a first pass I would look at:

- check all JS requests to see if they required
- check all CSS requests to see if they required
- run image compression on all images
- consider using `<link rel=preload>` to prioritize fetching resources that are currently requested later in page load
- cache policy on resources and assets (CSS, fonts, images, JS), there is none
- reduce the number of requests
- check for valid HTML
- check for valid CSS
- alt attributes for images
- check heading order(s)
