### ISSUE TITLE
Make URLs end with html

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#258]
Make all sub pages end with `.html`

**Comment by edhenderson** [comment]
@davidgatti I think it would be best for you to explain what you mean here? What is a sub page? Maybe give me a list of pages you need moved. I don't want to move some that don't need moved. Thanks!

**Comment by davidgatti** [comment]
For example: `http://localhost:4000/schedule/` should be `http://localhost:4000/schedule.html`, `http://localhost:4000/contact/` should be `http://localhost:4000/contact.html` etc.
