### ISSUE TITLE
A quote style text

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#262]
Is there a more quote like style in the template that could be used here?

![Screen Shot 2020-11-18 at 11 31 21 AM](https://user-images.githubusercontent.com/411114/99519851-ada27000-2992-11eb-9005-e7a4d0a2268d.png)

**Comment by edhenderson** [comment]
![Screenshot 2020-11-22 at 18 19 41](https://user-images.githubusercontent.com/1378582/99911903-5a605280-2cef-11eb-9819-14e399309073.png)

I had another look through the theme and I could not find one. The one I am using for this page is from the theme, see the screengrab with theme CSS and markup.

What did you have in mind, we can always do something custom?

**Comment by davidgatti** [comment]
In this case, just do italic.
