### ISSUE TITLE
Remove one drop down from the contact page

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#264]
For the industry I'd like to have a list of buttons, that you can click to select, to represent the drop down that there is now.

![Screen Shot 2020-11-18 at 11 35 24 AM](https://user-images.githubusercontent.com/411114/99519986-d6c30080-2992-11eb-9326-4487713b1e28.png)

**Comment by edhenderson** [comment]
@davidgatti Is this something you seen in the theme? 

https://landkit.goodthemes.co/docs/buttons.html doesn't have a toggle?

I did see https://landkit.goodthemes.co/docs/switches.html

**Comment by davidgatti** [comment]
Sorry, right, this will require a customized button, with a radio button on the left side. And I'd go with the Extra Small button type for this one.

**Comment by edhenderson** [comment]
OK, I will see if I can combine the XS button with a radio button.
