### ISSUE TITLE
Article URL unreachable

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#277]
I just realized that you did brake the article URLs. Not sure when was this, but I just noticed this now. Bellow I show what is was, and what is it now. 

- how it was: https://consulting.0x4447.com/articles/how_to/how-to-hire-the-technical-team.html
- how it is: https://consulting.0x4447.com/how-to/2020/10/17/how-to-hire-the-technical-team.html

We need to return to what it was as soon as possible, since the linked article are not reachable anymore.

**Comment by edhenderson** [comment]
@davidgatti THis is not good, let me take a look now.

**Comment by edhenderson** [comment]
This can be closed now @davidgatti
