### ISSUE TITLE
Header flashes when reloading the page

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#279]
For the schedule and contact page the header flashes when loading the page, despite the article pages also has the paralax, and dose not have the same issue.

**Comment by davidgatti** [comment]
As discussed over the chat, this should be possible to fix.

**Comment by edhenderson** [comment]
I shall take a look today

**Comment by davidgatti** [comment]
I mean the article itself, this is an example of an article: https://consulting.0x4447.com/articles/how_to/how-to-lower-aws-costs.html

there are more of them if you visit this page: https://consulting.0x4447.com/articles.html

I asked to make the article header be converted to base64, after the new finding how it all works, this feature is not useful. and so I want you to roll back the support for base64 in the header for each individual article, so this feature is no more, so you just link to regular image files, as normal.

**Comment by edhenderson** [comment]
@davidgatti I've been unable to reproduce this. I also checked the code and there is no discernible difference. I've added a wee fade in animation to mask any flash caused by the parallax, does this help?

**Comment by davidgatti** [comment]
Remember to move the discussion to the PR once it is made.

**Comment by edhenderson** [comment]
Yes understood. I think I typed this before the PR. My apologies.
