### ISSUE TITLE
Remove completely base64 work for the articles

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#282]
@edhenderson after some consideration I decided to remove the idea of the Base64 approach for the ARTICLE section of the page. Because without the automation it this feature is no fun, and adds to much complexity to the mix. 

Sorry that you have to delete what you did :)

**Comment by edhenderson** [comment]
Do you mean the cover images or all 3 article images?

**Comment by davidgatti** [comment]
I mean the article itself, this is an example of an article: https://consulting.0x4447.com/articles/how_to/how-to-lower-aws-costs.html

there are more of them if you visit this page: https://consulting.0x4447.com/articles.html

I asked to make the article header be converted to base64, after the new finding how it all works, this feature is not useful. and so I want you to roll back the support for base64 in the header for each individual article, so this feature is no more, so you just link to regular image files, as normal.
