### ISSUE TITLE
Increase the size of the logos

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#285]
In PR #276 I replaced the logos to vectors. If you check the page that is live right now you will see the logos are bigger, then the one vector, I'd like for the logos to be bigger while not changing the position of the text bellow. So to use the upper space. I hope this makes sesne.

![Screen Shot 2021-03-06 at 11 35 57 AM](https://user-images.githubusercontent.com/411114/110203783-52788880-7e70-11eb-9ec7-a817910eaf1f.png)

**Comment by edhenderson** [comment]
@davidgatti PR #276 was never merged, is that right?

Do you want me to work on top of what is it in PRODUCTION right now or on your PR code?

**Comment by edhenderson** [comment]
Understood. I shall start on your branch, thanks.

**Comment by edhenderson** [comment]
Did this fix your request?

**Comment by davidgatti** [comment]
Yes

**Comment by x5hwuk7nc6jsudcc** [comment]
Resolved by https://github.com/0x4447-office/0x4447_webpage_consulting/pull/301
