### ISSUE TITLE
Center the text

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#287]
The text under the logo needs to be centered.

![Screen Shot 2021-03-06 at 11 27 47 AM](https://user-images.githubusercontent.com/411114/110203881-ac794e00-7e70-11eb-9a87-e43be17a7aba.png)

**Comment by davidgatti** [comment]
@edhenderson this feature also got lost in a PR

**Comment by edhenderson** [comment]
@davidgatti I checked the `master` branch, the commit (and change is definitely there). It was initially to center the text but you changed your mind and asked me to layout as per the template. Check https://github.com/0x4447-office/0x4447_webpage_consulting/pull/290 for the discussion. Hope that explains.

**Comment by edhenderson** [comment]
Did you manage to resolve this?

**Comment by davidgatti** [comment]
Yes, turns out the build was crasing after you added the version for ruby or jekyll
