### ISSUE TITLE
Back to the drop down

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#289]
I know :) but it is what it is ;) 

![Screen Shot 2021-03-06 at 11 26 08 AM](https://user-images.githubusercontent.com/411114/110203920-d5014800-7e70-11eb-992c-444dd014c67f.png)

**Comment by edhenderson** [comment]
😠 😄

**Comment by edhenderson** [comment]
Can be closed now.

**Comment by davidgatti** [comment]
@edhenderson one of the previous PR removed this change from the master branch, I need this re-added some how. and in a way that it won't delete any other new things.

**Comment by edhenderson** [comment]
@davidgatti I just checked the master branch and can see the commit. I also checked the site locally and the dropdown change is there. Let me know if you have any problems locating things.

**Comment by edhenderson** [comment]
Did you manage to resolve this?

**Comment by davidgatti** [comment]
Yes, turns out the build was crasing after you added the version for ruby or jekyll

**Comment by edhenderson** [comment]
Thats not great. Crashing? Wow. I'm sorry. That version was imposed by the libraries needing it as a minimum version. Dam, please remove.
