### ISSUE TITLE
Set a fixed top margin

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#298]
When there is a lot of text under the title, the top margin is the same as the bottom, but when there is little, then the title with the sub title is dragged down, I'd like for the title and sub title to have the same top margin regardles of how much text there is in the subtitle.

![Screen Shot 2021-05-27 at 4 36 49 AM](https://user-images.githubusercontent.com/411114/119758147-5a136080-bea6-11eb-831b-e59f9febe099.png)

**Comment by x5hwuk7nc6jsudcc** [comment]
The top margin looks the same to me regardless of change to heading/subtitle?

![image](https://user-images.githubusercontent.com/19599955/120121797-d086ca00-c1e8-11eb-8d29-62900982d639.png)

![image](https://user-images.githubusercontent.com/19599955/120121801-d7154180-c1e8-11eb-8b9a-363d42cfe10a.png)

**Comment by davidgatti** [comment]
I see, thank you for the extra screenshot, now it all start to make sense, so as you can see now more stuff makes no sense. 

- the left side of the box, has the margin off, if you look at my name at the bottom, you can see that the margin is smaller then the margin for the header part. The header section should have the same margin as the bottom one.
- the image should be hosted always to the top, with the same margins as the header as explained in the point above.

Only then this box will visually look consistent.

**Comment by x5hwuk7nc6jsudcc** [comment]
Resolved by https://github.com/0x4447-office/0x4447_webpage_consulting/pull/302
