### ISSUE TITLE
Make the images the same as the template.

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#299]
The original template has the images go beyond the main body of the text, can this by done, while we use markdown? I
m OK if I have to add some custom CSS to the image, as long as it can live within the markdonw. The template can be seen here: https://landkit.goodthemes.co/blog-post.html

![Screen Shot 2021-05-27 at 4 40 17 AM](https://user-images.githubusercontent.com/411114/119758269-8b8c2c00-bea6-11eb-8fab-4b7e2147462f.png)

**Comment by x5hwuk7nc6jsudcc** [comment]
Hi @davidgatti 
This sorts of things can be tricky to do with mark/inline html alone as normally you need to close the container, and then re-open the container. We should be able to do something though - can you send me a link to this page? Just pulled master and can't see it.

**Comment by davidgatti** [comment]
I was wondering if it is possible at build time just go over each file, search for the image tag, and attach a custom class to the images. If this is possible, i think this approach will be the cleanest and easiest, if not we can ditch the idea.

**Comment by x5hwuk7nc6jsudcc** [comment]
Just looking at the code, I think I can achieve a similar effect with css alone. I'll create a PR shortly.

**Comment by x5hwuk7nc6jsudcc** [comment]
Resolved by https://github.com/0x4447-office/0x4447_webpage_consulting/pull/300 which creates a new class `#uncontain` that alllows image to escape container. Can be used in Markdown as follows:

```markdown
![example](/assets/img/articles/the-best-serverless-database-combo-on-aws/s3_ddb_example.png#uncontain)
```
