### ISSUE TITLE
A better URL

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#34]
When you visti an article, this is the URL:

`https://consulting.0x4447.com/knoledge/should-i-go-all-in-with-serverless.html`

it is missing the `articles` part, so if possible I'd like to have:

`https://consulting.0x4447.com/articles/knoledge/should-i-go-all-in-with-serverless.html`

**Comment by davidgatti** [comment]
![Screen Shot 2020-04-06 at 11 46 57 PM](https://user-images.githubusercontent.com/411114/78608298-ef960000-7860-11ea-946d-4ced21d22a0a.png)

This did not fixed the problem you made the URL work anymore, please please check your work to make sure what you commit work as expected, this is a simple site, and you should have noticed that is is not working by just clicking around.

**Comment by tolgaouz** [comment]
I made sure that it was working but I always get confused about version control with git, I must've messed up while committing it. I should've checked it after the commit, sorry.
