### ISSUE TITLE
Site map has odd links

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#57]
This links make no sense, we need to generate actually what makes sense, see if there is a way to configure this.

```
<loc>http://localhost:4000/articles/2/</loc>
</url>
<url>
<loc>http://localhost:4000/assets/favicons/html_code.html</loc>
<lastmod>2020-04-11T18:02:14+02:00</lastmod>
</url>
<url>
<loc>http://localhost:4000/assets/libs/flickity-fade/sandbox/basic.html</loc>
<lastmod>2020-04-07T18:40:20+02:00</lastmod>
</url>
<url>
<loc>http://localhost:4000/assets/libs/typed.js/</loc>
<lastmod>2020-04-07T18:40:20+02:00</lastmod>
</url>
```

**Comment by tolgaouz** [comment]
fixed, created pr

**Comment by davidgatti** [comment]
@tolgaouz you changed how the URL works. The URL must have the extension `.html` and you removed it, so now the Article page once deploy don't work anymore. I had to roll back the site again.

**Comment by davidgatti** [comment]
The main problem is with the article page.

**Comment by davidgatti** [comment]
No need to work on this, for now the fixes causes issues with the site itself which is more important then a working sitemap.
