### ISSUE TITLE
Fixing all URLs to one standard

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#78]
What I want is the following: 

I don't want to use the `.html` extension, to achieve this we need to have a index.html file inside a folder, and the fodler name must be the name of the URL. For example 

- `schedule/index.html`
- `schedule/thankyou/index.html`
- `contact/index.html`

etc, similar to how it is done for the article pages. 

Also I don't know what is oging on with the Article section, but displaying the catogory is broken, the whole page is not rendered correctly, not to mention, that now the URL are wrong:

Now I see: http://localhost:4000/how_to/2020/03/15/how-to-lower-ec2-costs/

there is the data, and we did not have dated. 

this are the URLs that we had, and I shared with people already

- https://consulting.0x4447.com/articles/how_to/how-to-lower-ec2-costs.html
- https://consulting.0x4447.com/articles/knoledge/should-i-go-all-in-with-serverless.html
- https://consulting.0x4447.com/articles/knoledge/the-benefits-of-aws-organization.html

I want this drama with the URL to stop.

**Comment by davidgatti** [comment]
OK, I think I found the problem, and now understand how the permalink should work. So by adding permalink the idea is that a folder will be created, and a index file would be added there - which is what we want. I read this post: https://stackoverflow.com/a/21267633

The problem is, that this is not happening, if you check the _site folder, for example the contact page, is a html file in the root dirrectory, and not `contact/index.html`.

So this is right now the problem that we are facing that needs to be solved.

**Comment by tolgaouz** [comment]
This one should be fixed now with pull requests
