### ISSUE TITLE
Section in the article

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#83]
![Screen Shot 2020-05-03 at 9 43 50 PM](https://user-images.githubusercontent.com/411114/80924103-6c949680-8d87-11ea-8dbc-c01f48799e5b.png)

Would it be possible to have this section of the page as a separated view or whatever the name is. This way each article will have the same exact section? SO you edit in one and it will be edited everywhere?

**Comment by tolgaouz** [comment]
yep, sure. We can make it a component

**Comment by davidgatti** [comment]
O nice, perfect.
