### ISSUE TITLE
New input fields in the contact page

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_consulting#92]
In between the first row of inputs and the body, I want 3 new inputs:

- Company name
- Job Title
- A drop down with all the US stats. 

This inputs needs to be in the order as above, and one next to the other. With all the valdiation that makes Sense

And the data, should be added to the body. I will format that part, right no just append it.

**Comment by tolgaouz** [comment]
Like side by side or row by row?

**Comment by davidgatti** [comment]
Side by side, one after the other in one row.
